CREATE DATABASE keycloak;
CREATE USER keycloak WITH ENCRYPTED PASSWORD 'keycloak';
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

CREATE DATABASE quake;
CREATE USER quake WITH ENCRYPTED PASSWORD 'quake';
GRANT ALL PRIVILEGES ON DATABASE quake TO quake;

CREATE DATABASE bot-login;
CREATE USER bot-login WITH ENCRYPTED PASSWORD 'bot-login';
GRANT ALL PRIVILEGES ON DATABASE bot-login TO bot-login;
