version: '3'

services:

  reverse-proxy:
    depends_on:
      - auth
      - quake2
      - service
    build:
      context: .
      dockerfile: env/reverse-proxy/Dockerfile
    environment:
      UI_ADDR: host.docker.internal:4200
      SERVICE_ADDR: service:8080
    ports:
      - "443:443"
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  auth:
    depends_on:
      - postgres
    image: docker.quix.it/quake-auth:1.3.2
    environment:
      KEYCLOAK_USER: kadmin
      KEYCLOAK_PASSWORD: kadmin
      DOMAIN: localhost
      DB_ADDR: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      QUAKE_BASE_URL: http://quake2:8080/quake
      KEYCLOAK_FRONTEND_URL: https://localhost/auth/
    ports:
      - "8180:8080"


  quake-ui:
    depends_on:
     - quake2
    image: docker.quix.it/quix-quake-ui:1.3.7
    environment:
      API_DOMAIN: https://localhost
      UI_DOMAIN: https://localhost/quake

  quake2:
    depends_on:
      - postgres
      - auth
    image: docker.quix.it/quix-quake:2.1.0-postgres
    environment:
      QUAKE_DB_HOST: postgres:5432
      QUAKE_DB_USER: quake
      QUAKE_DB_PASS: quake
      QUAKE_AUTH_HOST: auth:8080
      QUAKE_BASE_HREF: /quake/
      QUARKUS_VERTX_CLUSTER_HOST: quake2
      QUARKUS_VERTX_CLUSTER_PORT: 9000
    ports:
      - "8280:8080"

  service:
    depends_on:
      - quake2
    image: docker.quix.it/quix-maven:3.8-amazoncorretto-17
    environment:
      QUAKE_AUTH_HOST: auth:8080
      QUARKUS_VERTX_CLUSTER_HOST: service
      QUARKUS_VERTX_CLUSTER_PORT: 9000
      BOT-LOGIN_DB_HOST: "postgres:5432"
    volumes:
      - "~/.m2:/root/.m2"
      - ".:/workspace"
    ports:
      - "8080:8080"
      - "5005:5005"
    command: "mvn clean compile quarkus:dev -DdebugHost=0.0.0.0 -Dquarkus.http.host=0.0.0.0"

  postgres:
    build: env/postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"

volumes:
  db-data:
